import { Glob } from 'bun';
import path from 'node:path';

const REPO_ROOT = path.resolve(import.meta.dir, '../..');
const OUTPUT_PATH = path.resolve(
  REPO_ROOT,
  'packages/i18n/src/i18n-resources.d.ts',
);

type JsonObject = Record<string, unknown>;

/**
 * Deep-merges multiple JSON objects into one. Later values
 * override earlier ones for leaf keys; objects are merged
 * recursively.
 */
function deepMerge(...sources: JsonObject[]): JsonObject {
  const result: JsonObject = {};

  for (const source of sources) {
    for (const [key, value] of Object.entries(source)) {
      if (
        typeof value === 'object' &&
        value !== null &&
        !Array.isArray(value) &&
        typeof result[key] === 'object' &&
        result[key] !== null &&
        !Array.isArray(result[key])
      ) {
        result[key] = deepMerge(result[key] as JsonObject, value as JsonObject);
      } else {
        result[key] = value;
      }
    }
  }

  return result;
}

/**
 * Converts a JSON object into a TypeScript type literal string
 * with the given indentation level.
 */
function toTypeLiteral(object: JsonObject, indent: number): string {
  const padding = '  '.repeat(indent);
  const entries = Object.entries(object);
  const lines: string[] = [];

  for (const [key, value] of entries) {
    // Quote keys that contain hyphens or other non-identifier chars
    const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`;

    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      lines.push(
        `${padding}${safeKey}: ${toTypeLiteral(value as JsonObject, indent + 1)};`,
      );
    } else {
      lines.push(`${padding}${safeKey}: string;`);
    }
  }

  const innerPadding = '  '.repeat(indent - 1);

  return `{\n${lines.join('\n')}\n${innerPadding}}`;
}

/**
 * Discovers all per-package en-GB locale files, deep-merges them,
 * and writes a type declaration to packages/i18n/src/i18n-resources.d.ts.
 */
export async function generateI18nTypes(): Promise<void> {
  const glob = new Glob('**/src/locales/en-GB.json');
  const merged: JsonObject = {};

  // Collect and merge all locale files
  for await (const filePath of glob.scan({
    cwd: REPO_ROOT,
    absolute: true,
  })) {
    // Skip node_modules
    if (filePath.includes('node_modules')) {
      continue;
    }

    const content = await Bun.file(filePath).json();

    Object.assign(merged, deepMerge(merged, content));
  }

  // Build the type literal for the merged resources
  const typeLiteral = toTypeLiteral(merged, 4);

  // Write the declaration file
  const output = `// Auto-generated by generate-i18n-types.ts — do not edit manually.
import 'i18next';

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'core';
    resources: {
      core: ${typeLiteral};
    };
  }
}
`;

  await Bun.write(OUTPUT_PATH, output);

  console.log(`Generated i18n types at ${OUTPUT_PATH}`);
}

// Run directly when executed as a script
if (import.meta.main) {
  await generateI18nTypes();
}
