export { closeOtherTabs } from './closeOtherTabs';
export { closeTabsToTheLeft } from './closeTabsToTheLeft';
export { closeTabsToTheRight } from './closeTabsToTheRight';
export { splitTabWithTab } from './splitTabWithTab';
export { ensureTab } from './ensureTab';
export { closeActiveTab } from './closeActiveTab';
export { activateTabByIndex } from './activateTabByIndex';
export { activateLastTab } from './activateLastTab';
export { useIsViewActive } from './useIsViewActive';
