export { registerSearchAdapter as registerAdapter } from './SearchAdapter';
export type { SearchAdapter } from './SearchAdapter';
export { initializeSearch as initialize } from './initializeSearch';
export { initializeSearchSync as initializeSync } from './initializeSearchSync';
export { searchFullText as fullText } from './searchFullText';
export { handleSearchInitialize } from './handleSearchInitialize';
export { handleSearchFullText } from './handleSearchFullText';
export { handleSearchSync } from './handleSearchSync';
export { handleSearchDatabaseSync } from './handleSearchDatabaseSync';
export { handleSearchReindexDatabase } from './handleSearchReindexDatabase';
export { searchConstants as constants } from './constants';
