export { deleteSelection as delete } from './deleteSelection';
export { getSelection as get } from './getSelection';
export { getSelectionIds as getIds } from './getSelectionPaths';
export { isSelected } from './isSelected';
export { selectionIsEmpty as isEmpty } from './selectionIsEmpty';
export { addToSelection as add } from './addToSelection';
export { removeFromSelection as remove } from './removeFromSelection';
export { select } from './select';
export { clearSelection as clear } from './clearSelection';
export { copySelection as copy } from './copySelection';
