export { createCollection as create } from './createCollection';
export { loadCollections as load } from './loadCollections';
export { hasCollectionsConfig as hasConfig } from './hasCollectionsConfig';
export { getCollectionsConfig as getConfig } from './getCollectionsConfig';
export { writeCollectionsConfig as writeConfig } from './writeCollectionsConfig';
export { getCollectionFromPath as getFromPath } from './getCollectionFromPath';
export { addCollectionFromPath as addFromPath } from './addCollectionFromPath';
export { collectionExists as exist } from './collectionExists';
export { getCollection as get } from './getCollection';
