// Auto-generated by generate-i18n-types.ts — do not edit manually.
import 'i18next';

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'core';
    resources: {
      core: {
        test: string;
        app: {
          version: string;
        };
        imageViewer: {
          previewMessage: string;
        };
        designStudio: {
          open: string;
          exit: string;
          resetView: string;
          zoomIn: string;
          zoomOut: string;
          zoomLevel: string;
        };
        actions: {
          back: string;
          cancel: string;
          clear: string;
          save: string;
          done: string;
          delete: string;
          remove: string;
          reset: string;
          edit: string;
          duplicate: string;
          manage: string;
          close: string;
        };
        error: {
          unknown: string;
          dirPathConflict: string;
        };
        formErrors: {
          required: string;
        };
        color: {
          default: string;
          inherit: string;
          transparent: string;
          blue: string;
          cyan: string;
          red: string;
          pink: string;
          purple: string;
          green: string;
          orange: string;
          yellow: string;
          brown: string;
          gray: string;
        };
        emojiPicker: {
          label: string;
          random: string;
          filter: string;
          skinTone: {
            none: string;
            dark: string;
            mediumDark: string;
            medium: string;
            mediumLight: string;
            light: string;
          };
        };
        iconPicker: {
          label: string;
          filter: string;
          random: string;
          change: string;
        };
        labels: {
          untitled: string;
          copy: string;
          optional: string;
          properties: string;
          designs: string;
          settings: string;
          queries: string;
          collections: string;
        };
        properties: {
          actions: {
            delete: {
              label: string;
              confirmation: {
                title: string;
                message: string;
                confirm: string;
              };
            };
            rename: {
              confirmation: {
                title: string;
                message: string;
                confirm: string;
              };
            };
            filter: string;
            add: string;
          };
          form: {
            name: {
              label: string;
              validation: {
                required: string;
                invalidCharacters: string;
                nameConflict: string;
              };
            };
            icon: {
              label: string;
            };
          };
          title: {
            name: string;
            description: string;
          };
          text: {
            name: string;
            description: string;
          };
          number: {
            name: string;
            description: string;
          };
          date: {
            name: string;
            description: string;
          };
          toggle: {
            name: string;
            description: string;
            defaultValue: {
              label: string;
              checked: string;
              unchecked: string;
            };
          };
          url: {
            name: string;
            description: string;
          };
          image: {
            name: string;
            description: string;
          };
          select: {
            name: string;
            description: string;
            options: {
              add: string;
              placeholder: string;
              addHint: string;
              nameEnterHint: string;
            };
            multiselect: {
              label: string;
            };
          };
          multiselect: {
            name: string;
            description: string;
          };
          icon: {
            name: string;
            description: string;
          };
          textFormatted: {
            name: string;
            description: string;
          };
          created: {
            name: string;
            description: string;
          };
          lastModified: {
            name: string;
            description: string;
          };
          file: {
            name: string;
            description: string;
          };
        };
        databases: {
          propertyFilesDirName: string;
          actions: {
            new: string;
            addProperty: string;
            addDesign: string;
            browseDesigns: string;
            addView: string;
            viewSettings: string;
          };
          entries: {
            actions: {
              previousEntry: string;
              nextEntry: string;
              openAsPage: string;
              entryOptions: string;
              goToDatabase: string;
            };
          };
          labels: {
            databases: string;
          };
          form: {
            labels: {
              fileType: string;
              anyFileType: string;
              customFileType: string;
              templates: string;
            };
            properties: {
              title: string;
              description: string;
            };
            getStarted: {
              title: string;
              template: string;
            };
            actions: {
              create: string;
            };
            name: {
              label: string;
              placeholder: string;
            };
            icon: {
              label: string;
            };
            entryName: {
              label: string;
              placeholder: string;
            };
            errors: {
              nameConflict: string;
              pathConflict: string;
            };
          };
          empty: {
            title: string;
            addViaButton: string;
            dropOrPaste: string;
          };
          entrySerializers: {
            markdown: {
              name: string;
              description: string;
            };
            json: {
              name: string;
              description: string;
            };
            yaml: {
              name: string;
              description: string;
            };
          };
          templates: {
            notes: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                content: {
                  name: string;
                };
                created: {
                  name: string;
                };
                lastModified: {
                  name: string;
                };
              };
            };
            books: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                author: {
                  name: string;
                };
                genre: {
                  name: string;
                };
                status: {
                  name: string;
                };
                rating: {
                  name: string;
                };
                publicationDate: {
                  name: string;
                };
                coverImage: {
                  name: string;
                };
              };
              options: {
                genre: {
                  fiction: string;
                  nonFiction: string;
                  scienceFiction: string;
                  fantasy: string;
                  mystery: string;
                  romance: string;
                  thriller: string;
                  horror: string;
                  biography: string;
                  selfHelp: string;
                };
                status: {
                  toRead: string;
                  reading: string;
                  finished: string;
                  abandoned: string;
                };
              };
            };
            weblinks: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                title: {
                  name: string;
                };
                url: {
                  name: string;
                };
                description: {
                  name: string;
                };
                image: {
                  name: string;
                };
                icon: {
                  name: string;
                };
                created: {
                  name: string;
                };
                lastModified: {
                  name: string;
                };
              };
              automations: {
                fetchWebpageMetadata: {
                  name: string;
                  description: string;
                };
              };
            };
            tasks: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                status: {
                  name: string;
                };
                priority: {
                  name: string;
                };
                dueDate: {
                  name: string;
                };
                created: {
                  name: string;
                };
                lastModified: {
                  name: string;
                };
              };
              options: {
                status: {
                  toDo: string;
                  inProgress: string;
                  done: string;
                };
                priority: {
                  low: string;
                  medium: string;
                  high: string;
                  urgent: string;
                };
              };
            };
            contacts: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                email: {
                  name: string;
                };
                phone: {
                  name: string;
                };
                company: {
                  name: string;
                };
                role: {
                  name: string;
                };
                photo: {
                  name: string;
                };
                notes: {
                  name: string;
                };
              };
            };
            recipes: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                image: {
                  name: string;
                };
                prepTime: {
                  name: string;
                };
                cookTime: {
                  name: string;
                };
                servings: {
                  name: string;
                };
                cuisine: {
                  name: string;
                };
                diet: {
                  name: string;
                };
                ingredients: {
                  name: string;
                };
                instructions: {
                  name: string;
                };
              };
              options: {
                cuisine: {
                  italian: string;
                  mexican: string;
                  chinese: string;
                  indian: string;
                  japanese: string;
                  french: string;
                  thai: string;
                  mediterranean: string;
                  american: string;
                };
                diet: {
                  vegetarian: string;
                  vegan: string;
                  glutenFree: string;
                  dairyFree: string;
                };
              };
            };
            movies: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                director: {
                  name: string;
                };
                genre: {
                  name: string;
                };
                status: {
                  name: string;
                };
                rating: {
                  name: string;
                };
                releaseDate: {
                  name: string;
                };
                poster: {
                  name: string;
                };
              };
              options: {
                genre: {
                  action: string;
                  comedy: string;
                  drama: string;
                  horror: string;
                  scienceFiction: string;
                  romance: string;
                  thriller: string;
                  documentary: string;
                  animation: string;
                  fantasy: string;
                };
                status: {
                  toWatch: string;
                  watching: string;
                  watched: string;
                };
              };
            };
            journal: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                date: {
                  name: string;
                };
                mood: {
                  name: string;
                };
                content: {
                  name: string;
                };
                created: {
                  name: string;
                };
              };
              options: {
                mood: {
                  great: string;
                  good: string;
                  okay: string;
                  bad: string;
                };
              };
            };
            projects: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                status: {
                  name: string;
                };
                priority: {
                  name: string;
                };
                startDate: {
                  name: string;
                };
                endDate: {
                  name: string;
                };
                description: {
                  name: string;
                };
                created: {
                  name: string;
                };
                lastModified: {
                  name: string;
                };
              };
              options: {
                status: {
                  planning: string;
                  active: string;
                  onHold: string;
                  completed: string;
                  archived: string;
                };
                priority: {
                  low: string;
                  medium: string;
                  high: string;
                };
              };
            };
            vocabulary: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                definition: {
                  name: string;
                };
                exampleSentence: {
                  name: string;
                };
                language: {
                  name: string;
                };
                partOfSpeech: {
                  name: string;
                };
              };
              options: {
                partOfSpeech: {
                  noun: string;
                  verb: string;
                  adjective: string;
                  adverb: string;
                  pronoun: string;
                  preposition: string;
                  conjunction: string;
                  interjection: string;
                };
              };
            };
            expenses: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                amount: {
                  name: string;
                };
                category: {
                  name: string;
                };
                date: {
                  name: string;
                };
                paymentMethod: {
                  name: string;
                };
              };
              options: {
                category: {
                  food: string;
                  transport: string;
                  housing: string;
                  entertainment: string;
                  shopping: string;
                  health: string;
                  utilities: string;
                  education: string;
                  other: string;
                };
                paymentMethod: {
                  cash: string;
                  card: string;
                  bankTransfer: string;
                };
              };
            };
            images: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                image: {
                  name: string;
                };
                caption: {
                  name: string;
                };
                dateTaken: {
                  name: string;
                };
                location: {
                  name: string;
                };
                created: {
                  name: string;
                };
              };
            };
            documents: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                file: {
                  name: string;
                };
                description: {
                  name: string;
                };
                category: {
                  name: string;
                };
                created: {
                  name: string;
                };
                lastModified: {
                  name: string;
                };
              };
              options: {
                category: {
                  work: string;
                  personal: string;
                  financial: string;
                  legal: string;
                  medical: string;
                  education: string;
                };
              };
            };
            videos: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                file: {
                  name: string;
                };
                thumbnail: {
                  name: string;
                };
                description: {
                  name: string;
                };
                duration: {
                  name: string;
                };
                created: {
                  name: string;
                };
              };
            };
            music: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                file: {
                  name: string;
                };
                artist: {
                  name: string;
                };
                album: {
                  name: string;
                };
                genre: {
                  name: string;
                };
                created: {
                  name: string;
                };
              };
              options: {
                genre: {
                  pop: string;
                  rock: string;
                  hiphop: string;
                  electronic: string;
                  jazz: string;
                  classical: string;
                  rnb: string;
                  country: string;
                  metal: string;
                  folk: string;
                };
              };
            };
          };
        };
        items: {
          labels: {
            items: string;
          };
        };
        designs: {
          labels: {
            new: string;
          };
          actions: {
            deleteConfirmation: {
              title: string;
              message: string;
              confirm: string;
            };
          };
          page: {
            name: string;
            new: string;
            description: string;
          };
          card: {
            name: string;
            new: string;
            description: string;
          };
          list: {
            name: string;
            new: string;
            description: string;
          };
          typography: {
            label: string;
            'container-hint': string;
            italic: string;
            underline: string;
            'font-family': {
              inherit: string;
              sans: string;
              serif: string;
              mono: string;
            };
            'font-weight': {
              '100': string;
              '200': string;
              '300': string;
              '400': string;
              '500': string;
              '600': string;
              '700': string;
              '800': string;
              '900': string;
              label: string;
              inherit: string;
            };
            'text-transform': {
              label: string;
              none: string;
              uppercase: string;
              lowercase: string;
              capitalize: string;
              'uppercase-short': string;
              'lowercase-short': string;
              'capitalize-short': string;
            };
            color: {
              label: string;
            };
            'font-size': {
              label: string;
            };
            'line-height': {
              label: string;
            };
            'letter-spacing': {
              label: string;
            };
            alignment: {
              label: string;
            };
            margin: {
              label: string;
              top: string;
              right: string;
              bottom: string;
              left: string;
              sync: string;
            };
            'text-align': {
              label: string;
              left: string;
              center: string;
              right: string;
              justify: string;
            };
          };
          layout: {
            label: string;
          };
          direction: {
            label: string;
            column: string;
            row: string;
          };
          gap: {
            label: string;
          };
          padding: {
            label: string;
            sync: string;
          };
          'min-height': {
            label: string;
          };
          placeholder: {
            label: string;
            placeholder: string;
            reroll: string;
          };
          static: {
            label: string;
            description: string;
          };
          'max-width': {
            label: string;
            placeholder: string;
          };
          truncate: {
            label: string;
            placeholder: string;
          };
          opacity: {
            label: string;
          };
          wrap: {
            label: string;
          };
          stretch: {
            label: string;
          };
          position: {
            label: string;
            cell: string;
          };
          'background-color': {
            label: string;
            color: string;
            opacity: string;
          };
          'background-image': {
            label: string;
          };
          'background-image-fit': {
            label: string;
            cover: string;
            contain: string;
            fill: string;
          };
          'backdrop-blur': {
            label: string;
          };
          'backdrop-brightness': {
            label: string;
          };
          'backdrop-blur-gradient': {
            label: string;
          };
          'backdrop-blur-gradient-direction': {
            label: string;
            'to-top': string;
            'to-bottom': string;
            'to-left': string;
            'to-right': string;
          };
          'backdrop-blur-gradient-extent': {
            label: string;
          };
          'number-format': {
            label: string;
            decimals: {
              label: string;
              placeholder: string;
            };
            'thousands-separator': {
              label: string;
              none: string;
              comma: string;
              period: string;
              space: string;
            };
            prefix: string;
            'prefix-style': string;
            suffix: string;
            'suffix-style': string;
            'sign-display': {
              label: string;
              auto: string;
              always: string;
              never: string;
            };
          };
          image: {
            placeholder: {
              label: string;
              select: string;
              change: string;
              remove: string;
              hint: string;
              browse: string;
              dialog: {
                title: string;
                selectNew: string;
                empty: string;
              };
            };
            round: {
              label: string;
            };
            sizing: {
              label: string;
              width: string;
              height: string;
              'width-placeholder': string;
              'height-placeholder': string;
              'max-width': string;
              'max-height': string;
              'max-width-placeholder': string;
              'max-placeholder': string;
              'toggle-unit': string;
              sync: string;
              'object-fit': {
                label: string;
                cover: string;
                contain: string;
                fill: string;
              };
            };
          };
          icon: {
            label: string;
            placeholder: {
              hint: string;
            };
            select: string;
            change: string;
            appearance: {
              label: string;
            };
            size: {
              label: string;
            };
            color: {
              label: string;
            };
            container: {
              label: string;
              size: string;
              'size-placeholder': string;
              radius: string;
              'radius-placeholder': string;
              'background-color': string;
              round: string;
            };
          };
          webview: {
            placeholder: string;
            'embed-blocked': string;
          };
          'url-display': {
            label: string;
          };
          'url-show-protocol': string;
          'url-show-subdomain': string;
          'url-show-domain': string;
          'url-show-tld': string;
          'url-show-path': string;
          border: {
            label: string;
            style: {
              label: string;
              none: string;
              solid: string;
              dashed: string;
              dotted: string;
            };
            width: {
              label: string;
            };
            radius: {
              label: string;
              'top-left': string;
              'top-right': string;
              'bottom-right': string;
              'bottom-left': string;
              sync: string;
            };
            color: {
              label: string;
            };
          };
        };
        queries: {
          labels: {
            query: string;
          };
        };
        calendar: {
          months: {
            january: string;
            february: string;
            march: string;
            april: string;
            may: string;
            june: string;
            july: string;
            august: string;
            september: string;
            october: string;
            november: string;
            december: string;
          };
          weekdays: {
            sunday: string;
            monday: string;
            tuesday: string;
            wednesday: string;
            thursday: string;
            friday: string;
            saturday: string;
          };
          weekdaysShort: {
            sunday: string;
            monday: string;
            tuesday: string;
            wednesday: string;
            thursday: string;
            friday: string;
            saturday: string;
          };
        };
        'design-studio': {
          labels: {
            designs: string;
            elements: string;
            layers: string;
          };
          elements: {
            container: string;
            text: string;
            title: string;
            'formatted-text': string;
            number: string;
            url: string;
            image: string;
            'image-viewer': string;
            icon: string;
            editor: string;
            webview: string;
            'text-placeholder': string;
            'container-empty-hint': string;
            'editor-preview-message': string;
            group: {
              content: string;
              media: string;
              layout: string;
            };
          };
        };
        toast: {
          close: string;
        };
        views: {
          labels: {
            view: string;
            new: string;
          };
          gallery: {
            name: string;
            description: string;
            options: {
              maxColumns: string;
              cardSize: string;
              small: string;
              medium: string;
              large: string;
              gap: string;
              compact: string;
              comfortable: string;
              spacious: string;
            };
          };
          table: {
            name: string;
            description: string;
            of: string;
            rowsPerPage: string;
            previousPage: string;
            nextPage: string;
            openEntry: string;
            resizeHandle: string;
            resizeHandleShiftHint: string;
            options: {
              title: string;
              columns: string;
              overflow: string;
              rowNumbers: string;
              rowSeparator: string;
              columnSeparator: string;
              highlightOnHover: string;
              zebraStripes: string;
              padding: string;
              compact: string;
              comfortable: string;
              spacious: string;
              showChips: string;
            };
            columnMenu: string;
            showChips: string;
            hideColumn: string;
          };
        };
        'design-property-mapping': {
          browser: {
            title: string;
            search: string;
            newDesign: string;
            emptyPreview: string;
            useDesign: string;
            propertiesTitle: string;
            backToDesigns: string;
            searchProperties: string;
            addProperty: string;
            dateGroup: string;
            zoom: string;
            highlightMapped: string;
            highlightUnmapped: string;
            mappingCounter: string;
          };
        };
        theme: {
          appearance: {
            action: string;
            label: string;
            system: string;
            light: string;
            dark: string;
          };
        };
      };
    };
  }
}
