// Auto-generated by generate-i18n-types.ts — do not edit manually.
import 'i18next';

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'core';
    resources: {
      core: {
        collections: {
          labels: {
            collection: string;
            collections: string;
          };
          entries: {
            actions: {
              add: string;
            };
            groups: {
              new: string;
              recent: string;
            };
            searchPlaceholder: string;
            empty: string;
          };
          selection: {
            addTo: string;
            searchPlaceholder: string;
            empty: string;
          };
          actions: {
            new: string;
            options: string;
            delete: {
              label: string;
              confirmation: {
                title: string;
                message: string;
                confirm: string;
              };
            };
          };
          list: {
            searchPlaceholder: string;
            empty: string;
            noResults: string;
          };
          details: {
            noSelection: string;
            icon: string;
            consumers: string;
            consumersEmpty: string;
            entries: string;
            entriesEmpty: string;
            selectEntry: string;
            selectAllEntries: string;
          };
        };
        test: string;
        app: {
          version: string;
        };
        navigation: {
          back: string;
          forward: string;
        };
        canvas: {
          fitView: string;
          grid: {
            label: string;
            none: string;
            dots: string;
            lines: string;
          };
          resetView: string;
          resetZoom: string;
          settings: string;
          snapToGrid: string;
          snapToObjects: string;
          zoomIn: string;
          zoomOut: string;
        };
        actions: {
          back: string;
          cancel: string;
          clear: string;
          selectAll: string;
          save: string;
          done: string;
          delete: string;
          remove: string;
          reset: string;
          edit: string;
          duplicate: string;
          manage: string;
          close: string;
          search: string;
          pickDate: string;
          swapSplitPosition: string;
          expand: string;
        };
        error: {
          unknown: string;
          dirPathConflict: string;
          invalidDirName: string;
        };
        formErrors: {
          required: string;
        };
        color: {
          default: string;
          inherit: string;
          transparent: string;
          blue: string;
          cyan: string;
          red: string;
          pink: string;
          purple: string;
          green: string;
          orange: string;
          yellow: string;
          brown: string;
          gray: string;
        };
        emojiPicker: {
          label: string;
          random: string;
          filter: string;
          skinTone: {
            action: string;
            none: string;
            dark: string;
            mediumDark: string;
            medium: string;
            mediumLight: string;
            light: string;
          };
        };
        iconPicker: {
          label: string;
          filter: string;
          random: string;
          change: string;
          defaultSet: string;
        };
        labels: {
          untitled: string;
          copy: string;
          increase: string;
          decrease: string;
          optional: string;
          properties: string;
          design: string;
          settings: string;
          templates: string;
          views: string;
        };
        properties: {
          actions: {
            delete: {
              label: string;
              confirmation: {
                title: string;
                message: string;
                confirm: string;
              };
            };
            rename: {
              confirmation: {
                title: string;
                message: string;
                confirm: string;
              };
            };
            filter: string;
            add: string;
          };
          form: {
            name: {
              label: string;
              validation: {
                required: string;
                invalidCharacters: string;
                nameConflict: string;
              };
            };
            icon: {
              label: string;
            };
          };
          title: {
            name: string;
            description: string;
          };
          text: {
            name: string;
            description: string;
          };
          number: {
            name: string;
            description: string;
          };
          date: {
            name: string;
            description: string;
          };
          toggle: {
            name: string;
            description: string;
            defaultValue: {
              label: string;
              checked: string;
              unchecked: string;
            };
          };
          url: {
            name: string;
            description: string;
          };
          color: {
            name: string;
            description: string;
          };
          image: {
            name: string;
            description: string;
          };
          select: {
            name: string;
            description: string;
            options: {
              add: string;
              placeholder: string;
              addHint: string;
              nameEnterHint: string;
            };
            multiselect: {
              label: string;
            };
          };
          multiselect: {
            name: string;
            description: string;
          };
          tags: {
            name: string;
            description: string;
          };
          icon: {
            name: string;
            description: string;
          };
          textFormatted: {
            name: string;
            description: string;
          };
          created: {
            name: string;
            description: string;
          };
          lastModified: {
            name: string;
            description: string;
          };
          file: {
            name: string;
            description: string;
          };
          collection: {
            name: string;
            description: string;
          };
          query: {
            name: string;
            description: string;
          };
        };
        databases: {
          propertyFilesDirName: string;
          actions: {
            new: string;
            addProperty: string;
            viewSettings: string;
            newEntry: string;
            configuration: string;
          };
          layouts: {
            databaseDefault: string;
          };
          layoutContexts: {
            card: {
              name: string;
            };
            'preview-card': {
              name: string;
            };
            list: {
              name: string;
            };
            'navigation-list': {
              name: string;
            };
            page: {
              name: string;
            };
            dialog: {
              name: string;
            };
            panel: {
              name: string;
            };
            'new-entry': {
              name: string;
            };
          };
          entryTemplates: {
            empty: string;
            actions: {
              add: string;
              delete: {
                confirmation: {
                  title: string;
                  message: string;
                  messageWithFiles: string;
                  confirm: string;
                };
              };
            };
            form: {
              name: {
                label: string;
                validation: {
                  required: string;
                };
              };
              defaultTitle: {
                label: string;
                placeholder: string;
              };
              chooseFile: string;
              chooseIcon: string;
              emptyValue: string;
            };
            menus: {
              blankEntry: string;
            };
          };
          entries: {
            actions: {
              previousEntry: string;
              nextEntry: string;
              openInNewTab: string;
              openInSplitView: string;
              entryOptions: string;
              goToDatabase: string;
              removeFromCollection: string;
              color: string;
              create: string;
            };
            errors: {
              titleInvalidCharacters: string;
              titleConflict: string;
            };
            toolbar: {
              newEntry: string;
              addExistingEntry: string;
            };
            selection: {
              count_one: string;
              count_other: string;
              clear: string;
              delete: string;
              deleteConfirmation: {
                title: string;
                message: string;
                confirm: string;
              };
            };
            pickers: {
              searchEntriesPlaceholder: string;
              searchDatabasesPlaceholder: string;
              entrySearchEmpty: string;
              databaseSearchEmpty: string;
              entryAddHint: string;
              entryAddMoreHint: string;
              newEntryCreateHint: string;
              newEntryCreateMoreHint: string;
            };
          };
          labels: {
            databases: string;
          };
          form: {
            labels: {
              fileType: string;
              anyFileType: string;
              customFileType: string;
              templates: string;
            };
            properties: {
              title: string;
              description: string;
            };
            actions: {
              create: string;
            };
            name: {
              label: string;
              placeholder: string;
            };
            icon: {
              label: string;
            };
            entryName: {
              label: string;
              placeholder: string;
            };
            errors: {
              nameConflict: string;
              pathConflict: string;
            };
          };
          settings: {
            label: string;
            description: string;
            actions: {
              delete: string;
            };
            sections: {
              general: string;
              interface: string;
              data: string;
              danger: string;
            };
            name: {
              description: string;
            };
            entryName: {
              description: string;
            };
            icon: {
              description: string;
            };
            entryOpenMode: {
              label: string;
              description: string;
              options: {
                dialog: {
                  label: string;
                  description: string;
                };
                panel: {
                  label: string;
                  description: string;
                };
                inPlace: {
                  label: string;
                  description: string;
                };
                newTab: {
                  label: string;
                  description: string;
                };
                split: {
                  label: string;
                  description: string;
                };
              };
            };
            hideViewsToolbar: {
              label: string;
              description: string;
            };
            entrySerializer: {
              label: string;
              description: string;
              error: {
                title: string;
                message: string;
              };
            };
            propertyFileStorage: {
              label: string;
              description: string;
              options: {
                root: {
                  label: string;
                  description: string;
                };
                common: {
                  label: string;
                  description: string;
                };
                property: {
                  label: string;
                  description: string;
                };
                entry: {
                  label: string;
                  description: string;
                };
              };
            };
            propertyFilesDir: {
              label: string;
              description: string;
            };
            delete: {
              description: string;
              button: string;
              confirmation: {
                title: string;
                message: string;
                confirm: string;
              };
            };
            clear: {
              title: string;
              description: string;
              button: string;
              confirmation: {
                title: string;
                message: string;
                confirm: string;
              };
            };
          };
          empty: {
            title: string;
            addViaButton: string;
            dropOrPaste: string;
          };
          entrySerializers: {
            markdown: {
              name: string;
              description: string;
            };
            json: {
              name: string;
              description: string;
            };
            yaml: {
              name: string;
              description: string;
            };
          };
          templates: {
            blank: {
              name: string;
              entryName: string;
              description: string;
            };
            notes: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                content: {
                  name: string;
                };
                created: {
                  name: string;
                };
                lastModified: {
                  name: string;
                };
              };
            };
            books: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                author: {
                  name: string;
                };
                genre: {
                  name: string;
                };
                status: {
                  name: string;
                };
                rating: {
                  name: string;
                };
                publicationDate: {
                  name: string;
                };
                coverImage: {
                  name: string;
                };
              };
              options: {
                genre: {
                  fiction: string;
                  nonFiction: string;
                  scienceFiction: string;
                  fantasy: string;
                  mystery: string;
                  romance: string;
                  thriller: string;
                  horror: string;
                  biography: string;
                  selfHelp: string;
                };
                status: {
                  toRead: string;
                  reading: string;
                  finished: string;
                  abandoned: string;
                };
              };
            };
            weblinks: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                title: {
                  name: string;
                };
                url: {
                  name: string;
                };
                description: {
                  name: string;
                };
                image: {
                  name: string;
                };
                icon: {
                  name: string;
                };
                created: {
                  name: string;
                };
                lastModified: {
                  name: string;
                };
              };
              automations: {
                fetchWebpageMetadata: {
                  name: string;
                  description: string;
                };
              };
            };
            tasks: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                status: {
                  name: string;
                };
                priority: {
                  name: string;
                };
                dueDate: {
                  name: string;
                };
                created: {
                  name: string;
                };
                lastModified: {
                  name: string;
                };
              };
              options: {
                status: {
                  toDo: string;
                  inProgress: string;
                  done: string;
                };
                priority: {
                  low: string;
                  medium: string;
                  high: string;
                  urgent: string;
                };
              };
            };
            contacts: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                email: {
                  name: string;
                };
                phone: {
                  name: string;
                };
                company: {
                  name: string;
                };
                role: {
                  name: string;
                };
                photo: {
                  name: string;
                };
                notes: {
                  name: string;
                };
              };
            };
            recipes: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                image: {
                  name: string;
                };
                prepTime: {
                  name: string;
                };
                cookTime: {
                  name: string;
                };
                servings: {
                  name: string;
                };
                cuisine: {
                  name: string;
                };
                diet: {
                  name: string;
                };
                ingredients: {
                  name: string;
                };
                instructions: {
                  name: string;
                };
              };
              options: {
                cuisine: {
                  italian: string;
                  mexican: string;
                  chinese: string;
                  indian: string;
                  japanese: string;
                  french: string;
                  thai: string;
                  mediterranean: string;
                  american: string;
                };
                diet: {
                  vegetarian: string;
                  vegan: string;
                  glutenFree: string;
                  dairyFree: string;
                };
              };
            };
            movies: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                director: {
                  name: string;
                };
                genre: {
                  name: string;
                };
                status: {
                  name: string;
                };
                rating: {
                  name: string;
                };
                releaseDate: {
                  name: string;
                };
                poster: {
                  name: string;
                };
              };
              options: {
                genre: {
                  action: string;
                  comedy: string;
                  drama: string;
                  horror: string;
                  scienceFiction: string;
                  romance: string;
                  thriller: string;
                  documentary: string;
                  animation: string;
                  fantasy: string;
                };
                status: {
                  toWatch: string;
                  watching: string;
                  watched: string;
                };
              };
            };
            journal: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                date: {
                  name: string;
                };
                mood: {
                  name: string;
                };
                content: {
                  name: string;
                };
                created: {
                  name: string;
                };
              };
              options: {
                mood: {
                  great: string;
                  good: string;
                  okay: string;
                  bad: string;
                };
              };
            };
            projects: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                status: {
                  name: string;
                };
                priority: {
                  name: string;
                };
                startDate: {
                  name: string;
                };
                endDate: {
                  name: string;
                };
                description: {
                  name: string;
                };
                created: {
                  name: string;
                };
                lastModified: {
                  name: string;
                };
              };
              options: {
                status: {
                  planning: string;
                  active: string;
                  onHold: string;
                  completed: string;
                  archived: string;
                };
                priority: {
                  low: string;
                  medium: string;
                  high: string;
                };
              };
            };
            vocabulary: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                definition: {
                  name: string;
                };
                exampleSentence: {
                  name: string;
                };
                language: {
                  name: string;
                };
                partOfSpeech: {
                  name: string;
                };
              };
              options: {
                partOfSpeech: {
                  noun: string;
                  verb: string;
                  adjective: string;
                  adverb: string;
                  pronoun: string;
                  preposition: string;
                  conjunction: string;
                  interjection: string;
                };
              };
            };
            expenses: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                amount: {
                  name: string;
                };
                category: {
                  name: string;
                };
                date: {
                  name: string;
                };
                paymentMethod: {
                  name: string;
                };
              };
              options: {
                category: {
                  food: string;
                  transport: string;
                  housing: string;
                  entertainment: string;
                  shopping: string;
                  health: string;
                  utilities: string;
                  education: string;
                  other: string;
                };
                paymentMethod: {
                  cash: string;
                  card: string;
                  bankTransfer: string;
                };
              };
            };
            images: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                image: {
                  name: string;
                };
                caption: {
                  name: string;
                };
                dateTaken: {
                  name: string;
                };
                location: {
                  name: string;
                };
                created: {
                  name: string;
                };
              };
            };
            documents: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                file: {
                  name: string;
                };
                description: {
                  name: string;
                };
                category: {
                  name: string;
                };
                created: {
                  name: string;
                };
                lastModified: {
                  name: string;
                };
              };
              options: {
                category: {
                  work: string;
                  personal: string;
                  financial: string;
                  legal: string;
                  medical: string;
                  education: string;
                };
              };
            };
            videos: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                file: {
                  name: string;
                };
                thumbnail: {
                  name: string;
                };
                description: {
                  name: string;
                };
                duration: {
                  name: string;
                };
                created: {
                  name: string;
                };
              };
            };
            music: {
              name: string;
              entryName: string;
              description: string;
              properties: {
                file: {
                  name: string;
                };
                artist: {
                  name: string;
                };
                album: {
                  name: string;
                };
                genre: {
                  name: string;
                };
                created: {
                  name: string;
                };
              };
              options: {
                genre: {
                  pop: string;
                  rock: string;
                  hiphop: string;
                  electronic: string;
                  jazz: string;
                  classical: string;
                  rnb: string;
                  country: string;
                  metal: string;
                  folk: string;
                };
              };
            };
          };
          design: {
            noDesigns: string;
            selectDesign: string;
            actions: {
              edit: string;
              back: string;
            };
            mapping: {
              title: string;
              none: string;
              noProperties: string;
              noCompatible: string;
              description: string;
            };
            defaultLayouts: {
              title: string;
              description: string;
              noCompatible: string;
            };
            entryColor: {
              title: string;
              description: string;
              label: string;
            };
          };
        };
        items: {
          labels: {
            items: string;
          };
        };
        editor: {
          blockActions: {
            turnInto: string;
            copy: string;
            duplicate: string;
            delete: string;
          };
          blockGutter: {
            insert: string;
            select: string;
          };
          blockMenu: {
            hint: string;
          };
          linkMenu: {
            link: string;
            placeholder: string;
            webpage: string;
            noResults: string;
            hint: string;
          };
          frames: {
            taskItem: string;
          };
          table: {
            addColumn: string;
            rowOptions: string;
            columnOptions: string;
            insertRowAbove: string;
            insertRowBelow: string;
            deleteRow: string;
            insertColumnLeft: string;
            insertColumnRight: string;
            deleteColumn: string;
            alignNone: string;
            alignLeft: string;
            alignCenter: string;
            alignRight: string;
          };
          marks: {
            bold: string;
            italic: string;
            strikethrough: string;
            code: string;
          };
          elements: {
            paragraph: {
              name: string;
              keywords: string;
            };
            'heading-1': {
              name: string;
              keywords: string;
            };
            'heading-2': {
              name: string;
              keywords: string;
            };
            'heading-3': {
              name: string;
              keywords: string;
            };
            'heading-4': {
              name: string;
              keywords: string;
            };
            'heading-5': {
              name: string;
              keywords: string;
            };
            'heading-6': {
              name: string;
              keywords: string;
            };
            code: {
              name: string;
              language: string;
              keywords: string;
            };
            math: {
              name: string;
              keywords: string;
            };
            'inline-math': {
              name: string;
              keywords: string;
            };
            'thematic-break': {
              name: string;
              keywords: string;
            };
            blockquote: {
              name: string;
              keywords: string;
            };
            'list-item': {
              name: string;
              keywords: string;
            };
            'ordered-list-item': {
              name: string;
              keywords: string;
            };
            'task-list-item': {
              name: string;
              keywords: string;
            };
            table: {
              name: string;
              keywords: string;
            };
          };
        };
        designs: {
          name: string;
          new: string;
          roles: {
            heading: {
              label: string;
            };
            'page-content': {
              label: string;
            };
          };
          roleVariants: {
            sm: string;
            md: string;
            lg: string;
            default: string;
            regular: string;
            muted: string;
            accent: string;
          };
          roleVariantAxes: {
            size: string;
            colour: string;
          };
          propertyElements: {
            variants: {
              plain: string;
              short: string;
              long: string;
              subtitle: string;
              caption: string;
              quote: string;
              sm: string;
              md: string;
              lg: string;
              'badges-sm': string;
              badges: string;
              'badges-lg': string;
              text: string;
              'url-text': string;
              link: string;
              webview: string;
              image: string;
              viewer: string;
              field: string;
              'multiline-field': string;
              editor: string;
              display: string;
            };
            descriptions: {
              'url-text': string;
              link: string;
              webview: string;
              image: string;
              viewer: string;
              field: string;
              'multiline-field': string;
              editor: string;
              display: string;
            };
            samples: {
              short: string;
              long: string;
              subtitle: string;
              caption: string;
              quote: string;
              title: string;
              select: string;
              field: string;
              'multiline-field': string;
            };
          };
          layouts: {
            empty: string;
            labels: {
              add: string;
            };
            actions: {
              deleteConfirmation: {
                title: string;
                message: string;
                confirm: string;
              };
            };
            page: {
              name: string;
              label: string;
              description: string;
            };
            card: {
              name: string;
              label: string;
              description: string;
            };
            list: {
              name: string;
              label: string;
              description: string;
            };
            space: {
              name: string;
              label: string;
              description: string;
            };
          };
          typography: {
            label: string;
            'container-hint': string;
            italic: string;
            underline: string;
            'font-family': {
              inherit: string;
              sans: string;
              serif: string;
              mono: string;
            };
            'font-weight': {
              '100': string;
              '200': string;
              '300': string;
              '400': string;
              '500': string;
              '600': string;
              '700': string;
              '800': string;
              '900': string;
              label: string;
              inherit: string;
            };
            'text-transform': {
              label: string;
              none: string;
              uppercase: string;
              lowercase: string;
              capitalize: string;
              'uppercase-short': string;
              'lowercase-short': string;
              'capitalize-short': string;
            };
            color: {
              label: string;
            };
            'font-size': {
              label: string;
            };
            'line-height': {
              label: string;
            };
            'letter-spacing': {
              label: string;
            };
            alignment: {
              label: string;
            };
            'alignment-margin': {
              label: string;
            };
            margin: {
              label: string;
              top: string;
              right: string;
              bottom: string;
              left: string;
              sync: string;
            };
            'margin-bottom': {
              label: string;
            };
            'text-align': {
              label: string;
              left: string;
              center: string;
              right: string;
              justify: string;
            };
          };
          layout: {
            label: string;
          };
          'page-panels': {
            label: string;
            content: {
              label: string;
            };
            left: {
              label: string;
            };
            right: {
              label: string;
            };
          };
          direction: {
            label: string;
            column: string;
            row: string;
          };
          gap: {
            label: string;
          };
          padding: {
            label: string;
            sync: string;
          };
          'min-height': {
            label: string;
          };
          placeholder: {
            label: string;
            placeholder: string;
            reroll: string;
          };
          'clear-custom-styling': string;
          'max-width': {
            label: string;
            placeholder: string;
          };
          truncate: {
            label: string;
            placeholder: string;
          };
          opacity: {
            label: string;
          };
          wrap: {
            label: string;
          };
          stretch: {
            label: string;
          };
          position: {
            label: string;
            cell: string;
          };
          'background-color': {
            label: string;
            color: string;
            opacity: string;
          };
          'background-image': {
            label: string;
          };
          'background-image-fit': {
            label: string;
            cover: string;
            contain: string;
            fill: string;
          };
          'backdrop-blur': {
            label: string;
          };
          'backdrop-brightness': {
            label: string;
          };
          'backdrop-blur-gradient': {
            label: string;
          };
          'backdrop-blur-gradient-direction': {
            label: string;
            'to-top': string;
            'to-bottom': string;
            'to-left': string;
            'to-right': string;
          };
          'backdrop-blur-gradient-extent': {
            label: string;
          };
          'number-format': {
            label: string;
            decimals: {
              label: string;
              placeholder: string;
            };
            'thousands-separator': {
              label: string;
              none: string;
              comma: string;
              period: string;
              space: string;
            };
            prefix: string;
            'prefix-style': string;
            suffix: string;
            'suffix-style': string;
            'sign-display': {
              label: string;
              auto: string;
              always: string;
              never: string;
            };
          };
          'date-format': {
            label: string;
            mode: {
              date: string;
              relative: string;
            };
            'show-time': string;
          };
          image: {
            label: string;
            placeholder: {
              select: string;
              change: string;
              remove: string;
              hint: string;
              browse: string;
              dialog: {
                title: string;
                selectNew: string;
                empty: string;
              };
            };
            round: {
              label: string;
            };
            sizing: {
              label: string;
              width: string;
              height: string;
              'width-placeholder': string;
              'height-placeholder': string;
              'max-width': string;
              'max-height': string;
              'max-width-placeholder': string;
              'max-placeholder': string;
              'toggle-unit': string;
              sync: string;
              'object-fit': {
                label: string;
                cover: string;
                contain: string;
                fill: string;
              };
            };
          };
          icon: {
            label: string;
            placeholder: {
              hint: string;
            };
            select: string;
            change: string;
            appearance: {
              label: string;
            };
            size: {
              label: string;
            };
            color: {
              label: string;
            };
            container: {
              label: string;
              size: string;
              'size-placeholder': string;
              radius: string;
              'radius-placeholder': string;
              'background-color': string;
              round: string;
            };
          };
          webview: {
            placeholder: string;
            'embed-blocked': string;
          };
          view: {
            placeholder: string;
            viewType: {
              label: string;
            };
          };
          'url-display': {
            label: string;
          };
          'url-show-protocol': string;
          'url-show-subdomain': string;
          'url-show-domain': string;
          'url-show-tld': string;
          'url-show-path': string;
          border: {
            label: string;
            style: {
              label: string;
              none: string;
              solid: string;
              dashed: string;
              dotted: string;
            };
            width: {
              label: string;
              sync: string;
            };
            radius: {
              label: string;
              'top-left': string;
              'top-right': string;
              'bottom-right': string;
              'bottom-left': string;
              sync: string;
            };
            color: {
              label: string;
            };
          };
          property: {
            label: string;
            none: string;
            noCompatible: string;
          };
          title: {
            label: string;
          };
          properties: {
            empty: string;
            actions: {
              add: string;
              delete: {
                confirmation: {
                  title: string;
                  message: string;
                  confirm: string;
                };
              };
            };
          };
          content: {
            label: string;
            placeholder: string;
            mode: {
              none: string;
              property: string;
              static: string;
            };
            emptyBehavior: {
              label: string;
              hide: string;
              placeholder: string;
            };
          };
          select: {
            placeholder: {
              label: string;
              description: string;
            };
          };
        };
        queries: {
          labels: {
            query: string;
            queries: string;
          };
          actions: {
            new: string;
          };
          list: {
            searchPlaceholder: string;
            empty: string;
            noResults: string;
          };
          details: {
            noSelection: string;
          };
          editor: {
            namePlaceholder: string;
            selectProperty: string;
            selectOperator: string;
            selectValue: string;
            valuePlaceholder: string;
            ascending: string;
            descending: string;
            propertyMismatch: string;
            outputEntries: string;
            searchEntries: string;
            removeNode: string;
            removeConnection: string;
            breakConnections: string;
            connectNearest: string;
            noProperties: string;
            connectNodes: string;
          };
          nodes: {
            source: string;
            filter: string;
            collectionFilter: string;
            sort: string;
            limit: string;
            results: string;
          };
          toolbar: {
            source: string;
            filter: string;
            collectionFilter: string;
            sort: string;
            limit: string;
          };
          sourcePicker: {
            select: string;
            searchPlaceholder: string;
            empty: string;
            groups: {
              databases: string;
              queries: string;
            };
          };
          collectionPicker: {
            select: string;
            anyCollection: string;
            groups: {
              collections: string;
            };
            searchPlaceholder: string;
            empty: string;
          };
          collectionOperators: {
            'is-in': string;
            'is-not-in': string;
          };
          operators: {
            equals: string;
            'not-equals': string;
            contains: string;
            'not-contains': string;
            'contains-any': string;
            'contains-all': string;
            'contains-none': string;
            'starts-with': string;
            'ends-with': string;
            'greater-than': string;
            'greater-than-or-equal': string;
            'less-than': string;
            'less-than-or-equal': string;
            is: string;
            'is-not': string;
            'is-before': string;
            'is-after': string;
            'is-on-or-before': string;
            'is-on-or-after': string;
            'is-true': string;
            'is-false': string;
            'is-empty': string;
            'is-not-empty': string;
          };
          dates: {
            today: string;
            yesterday: string;
            tomorrow: string;
            'one-week-ago': string;
            'one-week-from-now': string;
            'one-month-ago': string;
            'one-month-from-now': string;
            'last-days': string;
            'next-days': string;
            custom: string;
          };
          results: {
            empty: string;
          };
        };
        automations: {
          labels: {
            automation: string;
          };
        };
        calendar: {
          months: {
            january: string;
            february: string;
            march: string;
            april: string;
            may: string;
            june: string;
            july: string;
            august: string;
            september: string;
            october: string;
            november: string;
            december: string;
          };
          weekdays: {
            sunday: string;
            monday: string;
            tuesday: string;
            wednesday: string;
            thursday: string;
            friday: string;
            saturday: string;
          };
          weekdaysShort: {
            sunday: string;
            monday: string;
            tuesday: string;
            wednesday: string;
            thursday: string;
            friday: string;
            saturday: string;
          };
          previousMonth: string;
          nextMonth: string;
        };
        'design-studio': {
          labels: {
            designs: string;
            elements: string;
            layout: string;
            layouts: string;
            properties: string;
            views: string;
          };
          dashboard: {
            empty: string;
            noLayouts: string;
            layoutCount_one: string;
            layoutCount_other: string;
          };
          elements: {
            root: string;
            container: string;
            'page-panel': string;
            text: string;
            title: string;
            number: string;
            date: string;
            url: string;
            image: string;
            'image-viewer': string;
            icon: string;
            badges: string;
            webview: string;
            'formatted-text': string;
            editor: string;
            property: string;
            view: string;
            'container-empty-hint': string;
            group: {
              properties: string;
              elements: string;
              content: string;
              media: string;
              layout: string;
              views: string;
            };
          };
          mappable: {
            tooltip: string;
          };
          views: {
            new: string;
            existing: string;
            search: {
              placeholder: string;
            };
            empty: string;
            noMatches: string;
          };
        };
        toast: {
          close: string;
        };
        dataViews: {
          actions: {
            add: string;
            settings: string;
          };
          labels: {
            view: string;
            new: string;
            views: string;
          };
          dataSource: {
            placeholder: string;
            searchPlaceholder: string;
            empty: string;
            groups: {
              new: string;
              collections: string;
              queries: string;
              databases: string;
            };
            newCollection: string;
            newQuery: string;
          };
          canvas: {
            name: string;
            description: string;
            toolbarCards: string;
            showToolbarCard: string;
            toolbarCardTemplate: string;
            connectionArrows: string;
            connectionArrowsNone: string;
            connectionArrowsEnd: string;
            connectionArrowsBoth: string;
            connectionColor: string;
            connectionShape: string;
            connectionShapeCurved: string;
            connectionShapeStraight: string;
            connectionShapeDirect: string;
            connectionStyle: string;
            connectionStyleSolid: string;
            connectionStyleDashed: string;
            connectionStyleDotted: string;
            connectionThickness: string;
            connectionThicknessThin: string;
            connectionThicknessMedium: string;
            connectionThicknessThick: string;
            connectionDelete: string;
            alignLeft: string;
            alignCenter: string;
            alignRight: string;
            alignTop: string;
            alignMiddle: string;
            alignBottom: string;
            removeNodes: string;
            removeNodesHint: string;
            deleteEntries: {
              titleOne: string;
              title: string;
              messageOne: string;
              message: string;
              confirm: string;
            };
          };
          board: {
            name: string;
            description: string;
            label: string;
            addColumn: string;
            removeColumn: string;
            toolbarCards: string;
            showToolbarCard: string;
            toolbarCardTemplate: string;
          };
          gallery: {
            name: string;
            description: string;
            options: {
              cardWidth: string;
              gap: string;
              none: string;
              compact: string;
              comfortable: string;
              spacious: string;
            };
          };
          notebook: {
            name: string;
            description: string;
          };
          table: {
            name: string;
            description: string;
            of: string;
            rowsPerPage: string;
            previousPage: string;
            nextPage: string;
            openEntry: string;
            resizeHandle: string;
            resizeHandleShiftHint: string;
            options: {
              title: string;
              columns: string;
              overflow: string;
              rowNumbers: string;
              rowSeparator: string;
              columnSeparator: string;
              highlightOnHover: string;
              zebraStripes: string;
              padding: string;
              compact: string;
              comfortable: string;
              spacious: string;
              showChips: string;
            };
            columnMenu: string;
            showChips: string;
            hideColumn: string;
          };
          list: {
            searchPlaceholder: string;
            empty: string;
            noResults: string;
          };
          details: {
            noSelection: string;
          };
          missing: {
            message: string;
          };
          form: {
            name: {
              label: string;
              placeholder: string;
            };
            source: {
              label: string;
              collectionName: {
                label: string;
              };
              queryName: {
                label: string;
              };
            };
            actions: {
              create: string;
            };
          };
        };
        tags: {
          labels: {
            tag: string;
          };
        };
        onboarding: {
          welcome: {
            title: string;
            description: string;
            actions: {
              create: string;
              open: string;
            };
          };
          form: {
            title: string;
            name: {
              label: string;
              placeholder: string;
              default: string;
            };
            icon: {
              label: string;
            };
            location: {
              label: string;
              description: string;
              action: string;
            };
            actions: {
              back: string;
              create: string;
            };
            errors: {
              locationMissing: string;
              pathConflict: string;
            };
          };
          errors: {
            notAWorkspace: string;
            unknown: string;
          };
        };
        tabs: {
          new: string;
          newToTheLeft: string;
          newToTheRight: string;
          close: string;
          closeOthers: string;
          closeToTheLeft: string;
          closeToTheRight: string;
          duplicate: string;
          unsplit: string;
          split: {
            label: string;
            search: string;
            tabs: string;
          };
        };
        devTools: {
          labels: {
            devTools: string;
          };
          actions: {
            toggleSidebar: string;
            toggleWindowed: string;
          };
          panels: {
            logs: string;
            events: string;
            state: string;
            stories: string;
            tokens: string;
          };
          logs: {
            searchPlaceholder: string;
            empty: string;
            noMatches: string;
            levels: {
              all: string;
              log: string;
              info: string;
              warn: string;
              error: string;
            };
            actions: {
              clear: string;
              collapseAll: string;
              copy: string;
              sortNewestFirst: string;
              sortOldestFirst: string;
            };
          };
          events: {
            allEvents: string;
            searchPlaceholder: string;
            empty: string;
            noMatches: string;
            actions: {
              clear: string;
              edit: string;
              redispatch: string;
            };
            dispatch: {
              namePlaceholder: string;
              dataPlaceholder: string;
              dispatch: string;
              invalidData: string;
            };
          };
          stories: {
            searchPlaceholder: string;
          };
          state: {
            searchPlaceholder: string;
            storeSearchPlaceholder: string;
            noStores: string;
            emptyStore: string;
            noMatches: string;
          };
          shortcuts: {
            general: string;
            window: string;
            panels: string;
            toggle: string;
            help: string;
            close: string;
            windowed: string;
            sidebar: string;
            snapLeft: string;
            snapRight: string;
          };
          noPanels: string;
          screenshots: {
            pickHint: string;
            nameHint: string;
            namePlaceholder: string;
          };
        };
        desktopApp: {
          labels: {
            library: string;
          };
        };
        search: {
          open: string;
          placeholder: string;
          recent: string;
          noResults: string;
        };
        spaces: {
          labels: {
            spaces: string;
          };
          actions: {
            new: string;
          };
          list: {
            searchPlaceholder: string;
            empty: string;
            noResults: string;
          };
          details: {
            noSelection: string;
          };
          view: {
            notFound: string;
            actions: {
              edit: string;
              exitEditMode: string;
            };
          };
          templates: {
            blank: {
              name: string;
              description: string;
            };
          };
          form: {
            labels: {
              templates: string;
            };
            name: {
              label: string;
              placeholder: string;
            };
            icon: {
              label: string;
            };
            actions: {
              create: string;
            };
          };
        };
        designsStudio: {
          open: string;
          title: string;
          exit: string;
          backToDesigns: string;
          layouts: {
            new: string;
            backToLayouts: string;
          };
          tree: {
            dropHint: string;
          };
          webview: {
            placeholder: string;
            embedBlocked: string;
            iframeTitle: string;
          };
          view: {
            placeholder: string;
          };
          style: {
            default: {
              label: string;
              description: string;
            };
            defaultFont: {
              label: string;
              description: string;
            };
            sections: {
              typography: string;
              colour: string;
              spacing: string;
              border: string;
              size: string;
              contentWidth: string;
              background: string;
              layout: string;
              icon: string;
              iconContainer: string;
              image: string;
              frame: string;
              title: string;
              label: string;
              variants: string;
              variant: string;
              content: string;
              backgroundImage: string;
              backgroundBlur: string;
              padding: string;
              margin: string;
            };
            fields: {
              fontFamily: string;
              fontSize: string;
              fontWeight: string;
              lineHeight: string;
              letterSpacing: string;
              colour: string;
              textAlign: string;
              textTransform: string;
              italic: string;
              truncate: string;
              background: string;
              radius: string;
              borderStyle: string;
              borderWidth: string;
              padding: string;
              margin: string;
              gap: string;
              direction: string;
              align: string;
              spread: string;
              wrap: string;
              width: string;
              maxWidth: string;
              height: string;
              fixedHeight: string;
              fillRatio: string;
              minHeight: string;
              maxHeight: string;
              aspectRatio: string;
              orientation: string;
              objectFit: string;
              backgroundImageFit: string;
              iconSize: string;
              iconColour: string;
              variant: string;
              top: string;
              right: string;
              bottom: string;
              left: string;
              emphasis: string;
              backdropBrightness: string;
              backdropFade: string;
              backdropFadeDirection: string;
              backdropFadeRange: string;
              backdropTint: string;
              backdropTintStrength: string;
            };
            truncate: {
              off: {
                label: string;
                description: string;
              };
              lines_one: string;
              lines_other: string;
              decrease: string;
              increase: string;
            };
            toggle: {
              on: string;
              off: string;
            };
            fontFamily: {
              sans: {
                label: string;
                description: string;
              };
              serif: {
                label: string;
                description: string;
              };
              mono: {
                label: string;
                description: string;
              };
            };
            fontSize: {
              '2xs': {
                label: string;
                description: string;
              };
              xs: {
                label: string;
                description: string;
              };
              sm: {
                label: string;
                description: string;
              };
              base: {
                label: string;
                description: string;
              };
              md: {
                label: string;
                description: string;
              };
              lg: {
                label: string;
                description: string;
              };
              xl: {
                label: string;
                description: string;
              };
              '2xl': {
                label: string;
                description: string;
              };
              '3xl': {
                label: string;
                description: string;
              };
              '4xl': {
                label: string;
                description: string;
              };
              '5xl': {
                label: string;
                description: string;
              };
            };
            fontWeight: {
              regular: {
                label: string;
                description: string;
              };
              medium: {
                label: string;
                description: string;
              };
              semibold: {
                label: string;
                description: string;
              };
              bold: {
                label: string;
                description: string;
              };
            };
            lineHeight: {
              none: {
                label: string;
                description: string;
              };
              tight: {
                label: string;
                description: string;
              };
              snug: {
                label: string;
                description: string;
              };
              normal: {
                label: string;
                description: string;
              };
              relaxed: {
                label: string;
                description: string;
              };
              loose: {
                label: string;
                description: string;
              };
            };
            letterSpacing: {
              tight: {
                label: string;
                description: string;
              };
              normal: {
                label: string;
                description: string;
              };
              wide: {
                label: string;
                description: string;
              };
              wider: {
                label: string;
                description: string;
              };
            };
            measure: {
              full: {
                label: string;
                description: string;
              };
              narrow: {
                label: string;
                description: string;
              };
              content: {
                label: string;
                description: string;
              };
              wide: {
                label: string;
                description: string;
              };
            };
            width: {
              auto: {
                label: string;
                description: string;
              };
              full: {
                label: string;
                description: string;
              };
            };
            height: {
              fill: {
                label: string;
              };
              mode: {
                auto: {
                  label: string;
                  description: string;
                };
                fixed: {
                  label: string;
                  description: string;
                };
                fill: {
                  label: string;
                  description: string;
                };
                ratio: {
                  label: string;
                  description: string;
                };
              };
              noMinimum: {
                label: string;
              };
              noMaximum: {
                label: string;
              };
              decrease: string;
              increase: string;
              auto: {
                label: string;
              };
            };
            space: {
              '1': {
                label: string;
                hint: string;
              };
              '2': {
                label: string;
                hint: string;
              };
              '3': {
                label: string;
                hint: string;
              };
              '4': {
                label: string;
                hint: string;
              };
              '5': {
                label: string;
                hint: string;
              };
              '6': {
                label: string;
                hint: string;
              };
              '7': {
                label: string;
                hint: string;
              };
              '8': {
                label: string;
                hint: string;
              };
              none: string;
              px: {
                label: string;
                hint: string;
              };
              '0-5': {
                label: string;
                hint: string;
              };
              '0-75': {
                label: string;
                hint: string;
              };
              '1-5': {
                label: string;
                hint: string;
              };
              decrease: string;
              increase: string;
              sync: string;
            };
            size: {
              xs: {
                label: string;
                hint: string;
              };
              sm: {
                label: string;
                hint: string;
              };
              md: {
                label: string;
                hint: string;
              };
              lg: {
                label: string;
                hint: string;
              };
              xl: {
                label: string;
                hint: string;
              };
              '2xl': {
                label: string;
                hint: string;
              };
            };
            radius: {
              xs: {
                label: string;
                description: string;
              };
              sm: {
                label: string;
                description: string;
              };
              md: {
                label: string;
                description: string;
              };
              lg: {
                label: string;
                description: string;
              };
              xl: {
                label: string;
                description: string;
              };
              full: {
                label: string;
                description: string;
              };
            };
            borderWidth: {
              thin: {
                label: string;
                description: string;
              };
              medium: {
                label: string;
                description: string;
              };
              thick: {
                label: string;
                description: string;
              };
              accent: {
                label: string;
                description: string;
              };
              none: {
                label: string;
              };
              sync: string;
            };
            borderStyle: {
              solid: {
                label: string;
                description: string;
              };
              dashed: {
                label: string;
                description: string;
              };
              dotted: {
                label: string;
                description: string;
              };
            };
            iconSize: {
              '2xs': {
                label: string;
                description: string;
              };
              xs: {
                label: string;
                description: string;
              };
              sm: {
                label: string;
                description: string;
              };
              md: {
                label: string;
                description: string;
              };
              lg: {
                label: string;
                description: string;
              };
              xl: {
                label: string;
                description: string;
              };
            };
            textColour: {
              subtle: {
                label: string;
                description: string;
              };
              regular: {
                label: string;
                description: string;
              };
              solid: {
                label: string;
                description: string;
              };
            };
            rootBackground: {
              accent: {
                label: string;
                description: string;
              };
              transparent: {
                label: string;
                description: string;
              };
            };
            backgroundEmphasis: {
              none: {
                label: string;
                description: string;
              };
              subtle: {
                label: string;
                description: string;
              };
              regular: {
                label: string;
                description: string;
              };
              solid: {
                label: string;
                description: string;
              };
            };
            textAlign: {
              left: string;
              center: string;
              right: string;
              justify: string;
            };
            textTransform: {
              none: string;
              uppercase: string;
              uppercaseShort: string;
              lowercase: string;
              lowercaseShort: string;
              capitalize: string;
              capitalizeShort: string;
            };
            direction: {
              column: string;
              row: string;
            };
            labelVariant: {
              above: {
                label: string;
              };
              side: {
                label: string;
              };
              spread: {
                label: string;
              };
            };
            iconVariant: {
              side: {
                label: string;
              };
              above: {
                label: string;
              };
            };
            chromePreview: {
              value: string;
            };
            align: {
              start: string;
              center: string;
              end: string;
              stretch: string;
            };
            alignment: {
              vertical: {
                start: string;
                center: string;
                end: string;
                stretch: string;
              };
              horizontal: {
                start: string;
                center: string;
                end: string;
                stretch: string;
              };
              cell: string;
            };
            aspectRatio: {
              '9/16': {
                label: string;
              };
              '2/3': {
                label: string;
              };
              '3/4': {
                label: string;
              };
              '4/5': {
                label: string;
              };
              '1/1': {
                label: string;
              };
              '5/4': {
                label: string;
              };
              '4/3': {
                label: string;
              };
              '3/2': {
                label: string;
              };
              '16/9': {
                label: string;
              };
            };
            objectFit: {
              cover: {
                label: string;
                description: string;
              };
              contain: {
                label: string;
                description: string;
              };
              fill: {
                label: string;
                description: string;
              };
            };
            fillRatio: {
              '1': {
                label: string;
              };
              '2': {
                label: string;
              };
              '3': {
                label: string;
              };
              '4': {
                label: string;
              };
              decrease: string;
              increase: string;
            };
            orientation: {
              portrait: string;
              square: string;
              landscape: string;
            };
            aspectRatioSteps: {
              decrease: string;
              increase: string;
            };
            backdropBlur: {
              subtle: {
                label: string;
                description: string;
              };
              regular: {
                label: string;
                description: string;
              };
              strong: {
                label: string;
                description: string;
              };
            };
            fadeDirection: {
              'to-top': string;
              'to-bottom': string;
              'to-left': string;
              'to-right': string;
            };
            backdropBrightness: {
              decrease: string;
              increase: string;
            };
            backdropTint: {
              none: {
                label: string;
                description: string;
              };
              accent: {
                label: string;
                description: string;
              };
            };
            backdropTintStrength: {
              subtle: {
                label: string;
                description: string;
              };
              regular: {
                label: string;
                description: string;
              };
              strong: {
                label: string;
                description: string;
              };
            };
            borderEmphasis: {
              subtle: {
                label: string;
                description: string;
              };
              regular: {
                label: string;
                description: string;
              };
              strong: {
                label: string;
                description: string;
              };
            };
            panels: {
              left: string;
              right: string;
              width: string;
              defaultOpen: string;
            };
          };
          variants: {
            description: string;
          };
          locked: {
            description: string;
          };
          editor: {
            empty: string;
          };
          preview: {
            toggleTheme: string;
          };
        };
        settings: {
          title: string;
          open: string;
          back: string;
        };
        theme: {
          appearance: {
            action: string;
            label: string;
            system: string;
            light: string;
            dark: string;
          };
          imageDimming: {
            '1': string;
            '2': string;
            '3': string;
            label: string;
            off: string;
          };
          invertLightImages: {
            label: string;
          };
        };
      };
    };
  }
}
